# Generated by Django 5.1.1 on 2024-09-14 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_img', models.ImageField(blank=True, null=True, upload_to='users_avatars/', verbose_name='avatar image')),
                ('displayname', models.CharField(blank=True, max_length=50, verbose_name='display name')),
                ('info', models.TextField(blank=True, verbose_name='info')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'users profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
